### ISSUE TITLE
pip "instal" 

### ISSUE THREAD

**Issue by phdeac** [MQSSNTS/EstrategiaM#1]
pip instal urllib
ERROR: unknown command "instal" - maybe you meant "install"

e

pip install urllib
ERROR: Could not find a version that satisfies the requirement urllib (from versions: none)
ERROR: No matching distribution found for urllib

**Comment by MQSSNTS** [comment]
pip instal urllib
ERROR: unknown command "instal" - maybe you meant "install"

comando errado. O certo é pip install(com dois Ls) ""maybe you meant "install""

erro meu rsrs, o urllib ja vem com a livraria padrao do python rsrs, não precisa desse comando
